version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatty-postgres
    environment:
      POSTGRES_DB: chatty
      POSTGRES_USER: chatty
      POSTGRES_PASSWORD: chatty123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatty"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatty-network

volumes:
  postgres_data:
    driver: local

networks:
  chatty-network:
    driver: bridge
