version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatty-postgres
    environment:
      POSTGRES_DB: chatty
      POSTGRES_USER: chatty
      POSTGRES_PASSWORD: chatty123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatty"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatty-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatty-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/chatty
      DATABASE_USER: chatty
      DATABASE_PASSWORD: chatty123
      JWT_SECRET: your-secret-key-change-in-production
      JWT_ISSUER: chatty-app
      JWT_AUDIENCE: chatty-users
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - chatty-network

volumes:
  postgres_data:
    driver: local

networks:
  chatty-network:
    driver: bridge
